
import { doAction, loadConfig } from './a2a'


/**
 * run the a2a script generated by llm or hand written
 * 
 * @param {string} confDir the directory where the configuration files are stored
 * @param {string} codeFile the file that contains the a2a script
 * @param {object} params the parameters to pass to the a2a script
 * 
 * @returns {Promise<any>} 
 */
async function a2a(confDir, codeFile, params) {
  globalThis.doAction = doAction
  const config = loadConfig(confDir)
  const a2aModule = await import(codeFile)
  return await a2aModule.main(config, params)
}

export { a2a, doAction, loadConfig }