[package]
name = "a2a_types"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
anyhow.workspace = true
bytes.workspace = true
thiserror = "1"
