[package]
name = "a2a"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-js = { version = "0.4", features = ["bigint"] }
futures = "0.3"
tokio.workspace = true
anyhow.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive"] }
globwalk = "0.9"
a2a_tojson = { path = "../a2a_tojson" }
a2a_core = { path = "../a2a_core" }
a2a_types = { path = "../a2a_types" }
